### ISSUE TITLE
Bitte kick feature einbauen

### ISSUE THREAD

**Issue by marrobHD** [timmyrs/Varo#6]
Feature dass spieler nur 15 minuten am Tag spielen dürfen

**Comment by marrobHD** [comment]
Danke, das währe echt cool wenn du nochmal was mit Minecraft machst. Du könntest vielleicht auch ein Discord bot entwickeln, der den chat im MC Server und einem Discord channel syncronisiert. Wie das: https://github.com/destruc7i0n/shulker nur für die neuste MC Version

**Comment by timmyRS** [comment]
Das einzige was ich aktuell mit Minecraft mache ist https://github.com/timmyrs/Phpcraft

Ich glaube du wirst andere Plugins für deine zwecke finden müssen, aber irgendwann wird das feature vielleicht eingebaut.

**Comment by marrobHD** [comment]
Ok schade. Deins war das beste Varo Plugin was ich gefunden hatte

Am 01.08.2019 22:50 schrieb timmyrs <notifications@github.com>:

Das einzige was ich aktuell mit Minecraft mache ist https://github.com/timmyrs/Phpcraft

Ich glaube du wirst andere Plugins für deine zwecke finden müssen, aber irgendwann wird das feature vielleicht eingebaut.
